base/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^', include('home.urls', namespace='home')),
]

user/urls.py
from django.conf.urls import url
from .views import (
    index,
    login,
    do_login,
    create_conversation,
    serve_conversation,
    user_messages,
    join_conversation,
    get_conversation_messages,
    get_message,
    create_message
)

urlpatterns = [
    url(r'^login/', login, name='login'),
    url(r'^login-do/', do_login, name='do_login'),
    url(r'^messages/join/(?P<conversation_id>[^/]+)/', join_conversation, name='join_conversation'),
    url(r'^messages/', user_messages, name='messages'),
    url(r'^create-conversation/', create_conversation, name='create_conversation'),
    url(r'^conversation/message/get/(?P<message_id>[^/]+)/', get_message, name='get_message'),
    url(r'^conversation/message/new/(?P<conversation_id>[^/]+)/', create_message, name='create_message'),
    url(r'^conversation/messages/all/(?P<conversation_id>[^/]+)/', get_conversation_messages, name='conversation_messages'),
    url(r'^conversation/(?P<conversation_id>[^/]+)/', serve_conversation, name='serve_conversation'),
    url(r'^', index, name='index'),
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse, JsonResponse
from core.models import User, Conversation, Message
from django.contrib.auth import login as _login, authenticate
from django.db.models import Q
import json
from django.views.decorators.csrf import csrf_exempt
from channels import Group


def index(request):
    user = request.user
    return render(request, 'user_index.html', {'user': user})


def login(request):
    return render(request, 'user_login.html')


def do_login(request):
    try:
        post = request.POST
        username = post.get('username', None)
        password = post.get('password', None)
        assert username and password, "Username and password must be provided."
        assert User.objects.filter(username=username).exists(), "Incorrect username or password."
        user = User.objects.get(username=username)
        if user:
            auth_user = authenticate(username=user.username, password=password)
            if auth_user.is_authenticated():
                _login(request, auth_user)
                return redirect('user:index')

    except AssertionError as e:
        return HttpResponse(str(e))


def create_conversation(request):
    try:
        post = request.POST
        user = request.user
        title = post.get('title', None)
        tags = post.get('tags', None)

        assert title and tags, "Please provide a title and tags for this conversation."
        tags = ', '.join(tags.split(' '))
        patient = None
        professional = None
        if user.is_patient():
            patient = user
        conversation = Conversation.objects.create(
            title=title,
            patient=patient,
            professional=professional,
            tags=tags
        )
        try:
            Group('users').send({
                'text': json.dumps({
                    'message_type': 'notification.conversation.new',
                    'message_body': 'A new conversation is created',
                    'data_url': reverse('user:join_conversation', kwargs={'conversation_id': conversation.pk})
                })
            })
        except Exception as e:
            import traceback
            traceback.print_exc()
        return JsonResponse({
            'status': True,
            'data': {
                'id': conversation.pk.__str__(),
                'url': reverse('user:join_conversation', kwargs={'conversation_id': conversation.pk})
            },
            'error': None
        })

    except AssertionError as e:
        return JsonResponse({
            'status': False,
            'error': str(e)
        })

    except Exception as e:
        return JsonResponse({
            'status': False,
            'error': str(e)
        })


def serve_conversation(request, conversation_id):
    try:

        user = request.user
        conversation = Conversation.objects.get(pk=conversation_id)
        assert str(user.pk) in [str(conversation.patient.pk), str(conversation.professional.pk)], \
            "You are not part of this conversation"

        return render(request, 'user_conversation.html', {'conversation': conversation})

    except AssertionError as e:
        import traceback
        traceback.print_exc()
        return HttpResponse(str(e))

    except Exception as e:
        import traceback
        traceback.print_exc()
        return HttpResponse(str(e))


def user_messages(request):
    user = request.user

    if user.is_patient():
        conversations = Conversation.objects.filter(Q(patient=user) | Q(professional=user)).all()
    else:
        conversations = Conversation.objects.filter(Q(professional=user) | Q(status='pending')).all()

    return render(request, 'user_messages.html', {'conversations': conversations})


def join_conversation(request, conversation_id):
    try:

        user = request.user
        conversation = Conversation.objects.get(pk=conversation_id)
        if str(conversation.patient.pk) != str(user.pk):
            assert user.is_professional(), "You must be a validated professional."
        assert conversation.status not in ['closed', 'suspended'], "Conversation is not available"
        conversation.professional = user
        conversation.save()
        conversation.activate()

        try:
            Group('users').send({
                'text': json.dumps({
                    'message_type': 'notification.conversation.participiant.new',
                    'message_body': 'Someone joined conversation',
                    'data_url': reverse('user:join_conversation', kwargs={'conversation_id': conversation.pk})
                })
            })
        except Exception as e:
            import traceback
            traceback.print_exc()

        return redirect(reverse('user:serve_conversation', kwargs={'conversation_id': conversation.pk}))

    except AssertionError as e:
        import traceback
        traceback.print_exc()
        return HttpResponse(str(e))

    except Exception as e:
        import traceback
        traceback.print_exc()
        return HttpResponse(str(e))


def get_conversation_messages(request, conversation_id):
    try:
        user = request.user
        conversation = Conversation.objects.get(pk=conversation_id)
        assert str(user.pk) in [str(conversation.patient.pk), str(conversation.professional.pk)], \
            "You are not part of this conversation"

        messages = [{
            'id': message.pk.__str__(),
            'text': message.text,
            'username': message.user.username if message.user.is_professional() else conversation.patient_penname,
            'created_at': message.created_at.timestamp(),
            'is_patient': message.user.is_patient()
        } for message in conversation.message_set.all()]

        return JsonResponse({
            'status': True,
            'data': {
                'id': conversation.pk.__str__(),
                'title': conversation.title,
                'tags': conversation.tags,
                'messages': messages
            },
            'error': None
        })

    except AssertionError as e:
        return JsonResponse({
            'status': False,
            'error': str(e)
        })

    except Exception as e:
        return JsonResponse({
            'status': False,
            'error': str(e)
        })


def get_message(request, message_id):
    try:
        user = request.user
        message = Message.objects.get(pk=message_id)
        conversation = message.conversation
        assert str(user.pk) in [str(conversation.patient.pk), str(conversation.professional.pk)], \
            "You are not part of this conversation"

        return JsonResponse({
            'status': True,
            'data': {
                'id': message.pk.__str__(),
                'text': message.text,
                'username': message.user.username if message.user.is_professional() else conversation.patient_penname,
                'created_at': message.created_at.timestamp(),
                'is_patient': message.user.is_patient()
            },
            'error': None
        })

    except AssertionError as e:
        return JsonResponse({
            'status': False,
            'error': str(e)
        })

    except Exception as e:
        return JsonResponse({
            'status': False,
            'error': str(e)
        })

@csrf_exempt
def create_message(request, conversation_id):
    try:
        user = request.user
        conversation = Conversation.objects.get(pk=conversation_id)
        assert str(user.pk) in [str(conversation.patient.pk), str(conversation.professional.pk)], \
            "You are not part of this conversation"

        post = request.POST
        print(post)
        text = post.get('text')
        assert text, 'Empty message'
        message = Message.objects.create(
            conversation=conversation,
            user=user,
            text=text
        )

        try:
            Group('users').send({
                'text': json.dumps({
                    'message_type': 'notification.message.new',
                    'message_body': 'A new message is created',
                    'data_url': reverse('user:get_message', kwargs={'message_id': message.pk})
                })
            })
        except Exception as e:
            import traceback
            traceback.print_exc()

        return JsonResponse({
            'status': True,
            'data': {
                'id': message.pk.__str__(),
                'text': message.text,
                'username': message.user.username if message.user.is_professional() else conversation.patient_penname,
                'created_at': message.created_at.timestamp(),
                'is_patient': message.user.is_patient()
            },
            'error': None
        })

    except AssertionError as e:
        return JsonResponse({
            'status': False,
            'error': str(e)
        })

    except Exception as e:
        return JsonResponse({
            'status': False,
            'error': str(e)
        })

user/templates/partial_user_create_conversation.html
{% if request.user.is_patient %}
    <h3>Get started by clicking the button below. You will stay competely anonymous during this conversation.</h3>
    <h3>Be sure to fill out the information on what you need help with completely!</h3>
    <button class="ui centered button initiateConversationModel">
        <i class="large red heart middle aligned icon"></i>
        Find Help
    </button>
    <script>
        $(document).ready(function (e) {
            $('.initiateConversationModel').on('click', function (e) {
                $('.ui.modal.conversationModel').modal('show');
            })
        });

        function createConversation() {
            var form = $('.conversationModelForm');
            var errorElem = $('.conversationCreateFormError');
            errorElem.hide();
            var errorMessageDiv = $('.conversationCreateFormError p');
            console.log(form.serialize());
            $.ajax({
                type: "POST",
                url: "{% url 'user:create_conversation' %}",
                data: form.serialize(),
                // dataType: "text",
                success: function (resultData) {
                    console.log("Save Complete", resultData);
                    if (!resultData.status) {
                        errorMessageDiv.html(resultData.error);
                        errorElem.show();
                        return
                    }
                    window.location.href = resultData.data.url;
                }
            }).done(function (e) {
                $('.ui.modal.conversationModel').modal('show');
            });
        }
    </script>

    <div class="ui modal conversationModel">
        <i class="close icon"></i>
        <div class="header">
            Please tell us what you want to talk about
        </div>
        <div class="content">
            <div class="ui conversationCreateFormError error message" style="display: none">
                <p class="">You can always see me</p>
            </div>
            <form action="" class="ui form conversationModelForm" onsubmit="javascript:void(0)">
                {% csrf_token %}
                <div class="field">
                    <label for="">Please tell us what you want to talk about</label>
                    <input type="text" name="title" placeholder="tite">

                </div>
                <div class="field">
                    <label for="">Type in words that describe what you're going through.</label>
                    <input type="text" name="tags" placeholder="tags">
                </div>
            </form>

        </div>
        <div class="actions">
            <div class="ui black deny button">
                Cancel
            </div>
            <div onclick="createConversation()" class="ui positive right red labeled icon button">
                Create
                <i class="checkmark icon"></i>
            </div>
        </div>
    </div>
{% endif %}

user/templates/user_conversation.html
{% extends 'base.html' %}

{% block title %}
Hello {{ conversation.title }}
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="row">
        <div class="sixteen wide fluid column">
            <h2>Welcome back, {{ conversation.patient_penname }}</h2>
            <table class="ui celled padded table">
                <thead>
                    <tr>
                        <th class="single line">Conversation Name</th>
                        <th>Tags</th>
                        <th>Helper Name</th>

            </p>

            <div id="main"></div>
        </div>
        <script>
            var conversation_id = "{{ conversation.pk }}";
        </script>

        <script src="/static/dist/bundle.js"></script>
    </div>

</div>
{% endblock %}

user/templates/user_index.html
{% extends 'base.html' %}

{% block title %}
Hello {{ user.username }}
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="row">
        <div class="sixteen wide fluid column">
            <h3>
                This is your user dashboard
            </h3>
            <p>
                Handle user interaction here by roles
                <br>
                User: {{ user.username }}
                <br>
                User: {{ user.role }}
            </p>
        </div>
        <div class="sixteen wide fluid column">
            {% include 'partial_user_create_conversation.html' %}
        </div>


        <script src="https://cdn.agora.io/sdk/web/AgoraRTCSDK-2.3.1.js"></script> 
        <script src="/static/dist/bundle.js"></script>
        <script>
            var socket = new WebSocket('ws://' + window.location.host + '/user/');
            socket.onopen = function open() {
                console.log('WebSockets connection created.');
            };

            if (socket.readyState == WebSocket.OPEN) {
                socket.onopen();
                socket.send(JSON.stringify({
                    message: "yolo check me out in the WS frames "
                }));
            }
        </script>

    </div>

</div>
{% endblock %}

user/templates/user_login.html
{% extends 'base.html' %}

{% block title %}
Welcome to Protea
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="row">
        <div class="sixteen wide fluid column">
            <h3>
                Please login using form below
            </h3>
        </div>
        <div class="sixteen wide column">
            <form class="ui form" action="{% url 'user:do_login' %}" method="POST" enctype="application/x-www-form-urlencoded">
                {% csrf_token %}
                <div class="field">
                    <label>Username</label>
                    <input type="text" name="username" placeholder="Username">
                </div>
                <div class="field">
                    <label>Password</label>
                    <input type="password" name="password" placeholder="Password">
                </div>
                <div class="field">
                    <div class="ui checkbox">
                        <input type="checkbox" tabindex="0" class="hidden">
                        <label>I agree to the Terms and Conditions</label>
                    </div>
                </div>
                <button class="ui primary button" type="submit">Submit</button>
            </form>
        </div>


    </div>

</div>
{% endblock %}

user/templates/user_messages.html
{% extends 'base.html' %}

{% block title %}
Hello {{ user.username }}
{% endblock title %}

{% block content %}
<div class="ui grid">
    <div class="row">
        <div class="sixteen wide fluid column">
            <div class="find-help">
                <div class="ui centered card">
                    <div class="content">
                        {% if request.user.is_patient %}
                        <div class="item">
                
                            <div class="content">
                                {% include 'partial_user_create_conversation.html' %}
                            </div>
                        </div>
                        {% endif %}
                  </div>
                </div>

            </div>
            <div class="ui relaxed divided list">
                {% if conversations %}
                    {% for conversation in conversations %}
                        <div class="item">
                            <i class="large message middle aligned icon"></i>
                            <div class="content">
                                <a class="header" href="{% url 'user:join_conversation' conversation_id=conversation.pk %}">{{ conversation.title }}</a>
                                    {% if conversation.patient %}
                                        <div class="description">
                                            <i class="user icon"></i>
                                            <span>{{ conversation.patient_penname }}</span>
                                        </div>
                                        <div class="description">Preferred Language: {{ conversation.patient.language}}</div>
                                    {% endif %}
                                    {% if conversation.professional %}
                                        <div class="description">
                                            <i class="user icon"></i>
                                            <span>{{ conversation.professional_penname }}</span>
                                        </div>

                                    {% endif %}
                                    <div class="description">
                                        {% if request.user.is_professional %}
                                            {% if conversation.status == 'pending' and not conversation.professional %}
                                                <a href="{% url 'user:join_conversation' conversation_id=conversation.pk %}" class="ui tiny green secondary button">JOIN</a>
                                            {% endif %}
                                        {% endif %}
                                    </div>
                                    <div class="description">{{ conversation.tags }}</div>

                            </div>
                        </div>
                    {% endfor %}
                {% endif %}
                
            </div>
        </div>

    </div>

</div>
{% endblock %}