base/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include('user.urls', namespace='user')),
    url(r'^', include('home.urls', namespace='home')),
]

user/urls.py
from django.conf.urls import url
from .views import (
    index,
    login,
    do_login,
    create_conversation,
    serve_conversation,
    user_messages,
    join_conversation,
    get_conversation_messages,
    get_message,
    create_message
)

urlpatterns = [
    url(r'^login/', login, name='login'),
    url(r'^login-do/', do_login, name='do_login'),
    url(r'^messages/join/(?P<conversation_id>[^/]+)/', join_conversation, name='join_conversation'),
    url(r'^messages/', user_messages, name='messages'),
    url(r'^create-conversation/', create_conversation, name='create_conversation'),
    url(r'^conversation/message/get/(?P<message_id>[^/]+)/', get_message, name='get_message'),
    url(r'^conversation/message/new/(?P<conversation_id>[^/]+)/', create_message, name='create_message'),
    url(r'^conversation/messages/all/(?P<conversation_id>[^/]+)/', get_conversation_messages, name='conversation_messages'),
    url(r'^conversation/(?P<conversation_id>[^/]+)/', serve_conversation, name='serve_conversation'),
    url(r'^', index, name='index'),
]

core/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
import uuid
from django.utils import timezone
from django.conf import settings
from django.utils.crypto import get_random_string


class GenericBaseClass(models.Model):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    created_at = models.DateTimeField(db_index=True, default=timezone.now)
    is_deleted = models.BooleanField(default=False)

    class Meta:
        abstract = True
        get_latest_by = "created_at"


class User(AbstractBaseUser, GenericBaseClass, PermissionsMixin):
    objects = UserManager()
    REQUIRED_FIELDS = ['password']

    USERNAME_FIELD = 'username'
    USER_ROLE_CHOICES = (
        ('professional', 'Professional'),
        ('patient', 'Patient')
    )

    username = models.CharField(max_length=20, unique=True)
    role = models.CharField(choices=USER_ROLE_CHOICES, default='patient', max_length=20)
    language = models.CharField(max_length=50, default='English', null=False)

    def is_professional(self):
        return self.role == 'professional'

    def is_patient(self):
        return self.role == 'patient'

    def get_full_name(self):
        return self.username

    def get_short_name(self):
        return self.username


class Conversation(GenericBaseClass):
    STATUS_OPTIONS = (
        ('pending', 'Pending'),
        ('closed', 'Closed'),
        ('cancelled', 'Cancelled'),
        ('active', 'Active'),
        ('suspended', 'Suspended'),
    )
    # Professional|Patient value can be NULL because initially conversation is started by one party
    professional = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='professional', null=True)
    patient = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='patient', null=True)
    professional_penname = models.CharField(max_length=20,
                                            default=get_random_string,
                                            null=False)
    patient_penname = models.CharField(max_length=20,
                                       default=get_random_string,
                                       null=False)

    title = models.CharField(max_length=300, null=False, blank=True)
    tags = models.CharField(max_length=500, null=False, blank=True)
    is_patient_anonymous = models.BooleanField(default=True, null=False)
    status = models.CharField(choices=STATUS_OPTIONS, max_length=20, default='pending')


    def activate(self):
        self.status = 'active'
        self.save()

    def suspend(self):
        self.status = 'suspended'
        self.save()

    def cancel(self):
        self.status = 'cancelled'
        self.save()

    def close(self):
        self.status = 'closed'
        self.save()


class Message(GenericBaseClass):
    MESSAGE_STATUS_CHOICES = (
        ('active', 'Active'),
        ('suspended', 'Suspended'),
    )

    conversation = models.ForeignKey(Conversation)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    text = models.TextField(null=False, blank=True)
    status = models.CharField(choices=MESSAGE_STATUS_CHOICES, default='active', null=False, max_length=30)

core/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock title %}</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.2/jquery.min.js"></script>
    <script src="/static/semantic-ui/semantic.min.js"></script>
    <link rel="stylesheet" href="/static/semantic-ui/semantic.min.css"/>


</head>
<body>




<div class="ui container">
    <header>
        <div class="ui secondary  menu">
            <!-- <a class="active item">
                Home
            </a> -->

            <div class="right red menu">
                {% if request.user.is_authenticated %}
                <a class="item" href="{% url 'user:messages' %}">
                    Account
                </a>
                <a class="ui item">
                    Logout
                </a>
                {% else %}
                <a class="ui item" href="{% url 'user:login' %}">
                    Register
                </a>
                <a class="ui item" href="{% url 'user:login' %}">
                    Login
                </a>
                {% endif %}
            </div>
        </div>
    </header>
</div>
<br>
<div class="ui container">
    {% block content %}
    {% endblock content %}


    <script>
        var socket = new WebSocket('ws://' + window.location.host + '/user/');
        socket.onopen = function open() {
            console.log('WebSockets connection created.');
        };
        socket.onmessage = function (event) {
            console.log(event.data);
        }

        if (socket.readyState == WebSocket.OPEN) {
            socket.onopen();
            socket.send(JSON.stringify({
                message: "yolo check me out in the WS frames "
            }));
        }
    </script>
</div>

</body>
</html>